export const EVENTS = {
  OPEN_AUDIO_WIN: 'open:audio:window',
  STOP_AUDIO_WIN: 'stop:audio:window',
  COMMON_OPEN_DIR_DIALOG: 'common:open:dir:dialog',
  COMMON_GET_PLATFORM_INFO: 'common:get:platform_info',
  NETWORK_MAC_ADDRESS: 'network:mac:address',
  NETWORK_IP_SCAN: 'network:ip:scan',
  NETWORK_HOST_SCAN: 'network:host:scan',
  NOTIFICATION_SHOW: 'notification:show',
  MEDIA_VIDEO_TRIM: 'media:video:trim',
  MEDIA_VIDEO_AUDIO_MERGE: 'media:video:audio:merge',
  FILE_COPY_DIR_OR_FILE: 'file:copy:dir_or_file`',
  FILE_CREATE_DIR_BY_NEONATE: 'file:create:dir:neonate',
  FILE_LIST_DIR_BY_NEONATE: 'file:list:dir:neonate',
  FILE_LIST_DETAIL_BY_NEONATE: 'file:list:detail:neonate',
  FILE_RENAME_BY_NEONATE: 'file:rename:neonate',
  FILE_AND_DIR_REMOVE_BY_NEONATE: 'file_and_dir:remove:neonate',
  GLOBAL_CONF_UPDATE: 'global_conf:update',
  GLOBAL_CONF_GET: 'global_conf:get',
  REQ_DIR_SYNC: 'request:dir:sync',
  REQ_FILE_SYNC: 'request:file:sync',
  REQ_SYNC_STATUS: 'request:sync:status',
} as const

